//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIFI.Ausstellung.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIFI.Ausstellung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;aufgaben&gt;
        ///  &lt;aufgabe name=&quot;Abholungsverwaltung&quot; symbol=&quot;3&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Abholungsverwaltung&quot; /&gt;
        ///&lt;/aufgaben&gt;
        /// ähnelt.
        /// </summary>
        internal static string Abholung {
            get {
                return ResourceManager.GetString("Abholung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;aufgaben&gt;
        ///  &lt;aufgabe name=&quot;Offline&quot; symbol=&quot;3&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Offlineanzeige&quot; /&gt;
        ///&lt;/aufgaben&gt;
        /// ähnelt.
        /// </summary>
        internal static string Fehler {
            get {
                return ResourceManager.GetString("Fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;aufgaben&gt;
        ///  &lt;aufgabe name=&quot;Lieferverwaltung&quot; symbol=&quot;3&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Lieferverwaltung&quot; /&gt;
        ///&lt;/aufgaben&gt;
        /// ähnelt.
        /// </summary>
        internal static string Lieferung {
            get {
                return ResourceManager.GetString("Lieferung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;aufgaben&gt;
        ///  &lt;aufgabe name=&quot;Ausstellung&quot; symbol=&quot;3&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Ausstellung&quot; /&gt;
        ///  &lt;aufgabe name=&quot;Warenkorb&quot; symbol=&quot;$&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Warenkorb&quot; /&gt;
        ///  &lt;aufgabe name=&quot;Ausstellungsabschluss&quot; symbol=&quot;@&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Ausstellungsabschluss&quot; /&gt;
        ///&lt;/aufgaben&gt;
        /// ähnelt.
        /// </summary>
        internal static string Veranstaltung {
            get {
                return ResourceManager.GetString("Veranstaltung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;aufgaben&gt;
        ///  &lt;aufgabe name=&quot;Veranstaltungserstellung&quot; symbol=&quot;3&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Veranstaltungserstellung&quot; /&gt;
        ///  &lt;aufgabe name=&quot;Buchverwaltung&quot; symbol=&quot;$&quot; view=&quot;WIFI.Ausstellung.Views.Aufgaben.Buchverwaltung&quot; /&gt;
        ///&lt;/aufgaben&gt;
        /// ähnelt.
        /// </summary>
        internal static string Vorbereitung {
            get {
                return ResourceManager.GetString("Vorbereitung", resourceCulture);
            }
        }
    }
}
